// React/src/studentModal.js
import React from 'react';

const StudentModal = ({student, closeModal, status}) =>(
  <div className="modal" style={{ display: 'block' }}>
        <div className="modal-dialog">
            <div className="modal-content">
                <div className="modal-header">
                    <h5 className="modal-title">Detalles del estudiante</h5>
                    
                    <button type="button" className="close" onClick={closeModal}>
                        <span>&times;</span>
                    </button>
                </div>
                <div className="modal-body">
                    <h5>Infomación</h5>
                    <p><strong>Nombre del alumno:</strong> {student.name}</p>
                    <p><strong>Calificación:</strong> {student.score}</p>
                    <p><strong>Estado:</strong> {status}</p>
                    
                </div>
                
            </div>
        </div>
    </div>
);
export default StudentModal;

// Angular/src/app/components/student-modal/student-modal.component.ts
import {Component, Inject,OnInit} from '@angular/core';
import {MatDialog, MAT_DIALOG_DATA} from '@angular/material/dialog';
@Component({
  selector: 'modal',
  templateUrl: './student-modal.component.html',
  styleUrls: ['./student-modal.component.scss']
})
export class StudentModalComponent implements OnInit {

   constructor(@Inject(MAT_DIALOG_DATA) public data: any){
   }

  ngOnInit() {
  }




}

<div class="details bg-primary">
    <h1 mat-dialog-title class="details-title">Detalles del estudiante</h1>
</div>
<div class="information-section">
    <div mat-dialog-content>Informacion</div>
    <hr>
    <ul>
        <li mat-dialog-content>Nombre: <p class="information-data">{{data.name}}</p></li>
        
        <li mat-dialog-content>Calificacion: <p class="information-data">{{data.score}}</p></li>
        <li mat-dialog-content>Estado: <p class="information-data">{{data.status}}</p></li>
    </ul>
</div>
